exports.EXPIRE_TIME = '48h';
exports.EXPIRE_FORGOT_PASSWORD_EMAIL = 86400000;
exports.BYCRYPT_LENGTH = 12;
exports.PLATFORM_PASSWORD = 'mulu2020!!!';

exports.ROLE = {
  ADMIN: 'ADMIN',
  CONTACT: 'CONTACT',
  AGENT: 'AGENT'
}

exports.GENDER = {
  MALE: 'MALE',
  FEMALE: 'FEMALE'
}

exports.PROFESSION = {
  CORPORATE_FINANCE: 'CORPORATE_FINANCE',
  COMMERCIAL_BANKING: 'COMMERCIAL_BANKING',
  INVESTMENT_BANKING: 'INVESTMENT_BANKING',
  HEDGE_FUNDS: 'HEDGE_FUNDS',
  FINANCIAL_PLANNING: 'FINANCIAL_PLANNING'
}